version: '3.3'
services:

  ui:
    env_file: .env
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp
    networks:
      - front_net
    volumes:
      - ./ui:/home/app
    command: ["puma", "--debug", "-w", "2"]

  post:
    env_file: .env
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - front_net
      - back_net
    volumes:
      - ./post-py:/home/app
      
  comment:
    env_file: .env
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - back_net
    volumes:
      - ./comment:/home/app
    command: ["puma", "--debug", "-w", "2"]

